# Generated by Django 3.1 on 2021-05-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grc_common', '0002_auto_20210518_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
